version: 2
updates:
  - package-ecosystem: "maven"
    open-pull-requests-limit: 100
    directory: "/"
    schedule:
      interval: "daily"
      time: "06:00"
      timezone: "Europe/Berlin"
    allow:
      - dependency-type: "direct"
    labels:
      - "dependencies"
      - "automatic-merge"
#    groups:
#      minor-and-patch-version-updates:
#        update-types:
#        - "minor"
#        - "patch"
