sudo: false

language: java

jdk:
- oraclejdk8

branches:
  only:
  - develop
  - master
  - "/^v[0-9].*/"

cache:
  directories:
  - "$HOME/.m2"

install: true

before_script:
- export TZ=Europe/Berlin

script: mvn clean verify

deploy:
  provider: releases
  api_key:
    secure: EGwh3CyV0P6HpRgyDXDierokWn30DbVKsqeNmo7c6WMTGDr06gdmVOWd5Y5O/XS6Zz734O3bBKSUjlzRycF8zBi6ce858vwNgzWZX1dh4TZBybThRZJL5n2WMDF3IHun6w0jT0iabYOscBMhMeJPU1CdFrZ/N3qY060M6MHaTvNd91DlnZDV3plPxigNabeoa0EEUaREbatILpIpyxZ2DZ05GSzXhnm5EP5AYZ600wdm5rRhCR8KnStRCITz+AvVDP+Gzn8vrEYvcMtP0N76WQYPBSUErVajMHbdcQyLxVmtMFBumvRFb2DwEfsx+4Md0IxuJZYv4Kzqpm1v9ym0EF3ndOToqiXH/pBQ1y9E3B9/Ig+CuaiFA8kcZjSTw1/lw26Z+X8+2vXRhmiXUsj0zmAVF3G7En2JzTT5R18h15YJ9fq5tf8H8hgFNm04XbqFygW3OoxjwChG/Hkp1kcAVtsRvw86VjLFCUftHCOQA3JDcx1ncSjkLu+/hBXeSH7kyw3cFP6WyavAPE0ejB/JByiPaQbeNfYWhb9zy5gH1BVQpSAgxyKQBVTDwG6xQKqsLeBmXb8wpGlBH8zG8XK0eN5UwrXYJhZ1BS8KjAn/N6xczV+uczxeeFUK0N5Tktvfg/BJEVMFimjvVAb+sZ/bqut6IMq95H5KerMlF6fK/M8=
  file: "./target/*.zip"
  file_glob: true
  skip_cleanup: true
  on:
    repo: mathisdt/albumcreator
